package fpt.aptech.client.Model;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import java.util.List;




public class Classs {

    private Integer classsid;
    private String classsname;
    private EducationLevel levelid;
    private List<Subject> subjectList;
public  Classs(){

}

    public Integer getClasssid() {
        return classsid;
    }

    public void setClasssid(Integer classsid) {
        this.classsid = classsid;
    }

    public String getClasssname() {
        return classsname;
    }

    public void setClasssname(String classsname) {
        this.classsname = classsname;
    }

    public EducationLevel getLevelid() {
        return levelid;
    }

    public void setLevelid(EducationLevel levelid) {
        this.levelid = levelid;
    }

    public List<Subject> getSubjectList() {
        return subjectList;
    }

    public void setSubjectList(List<Subject> subjectList) {
        this.subjectList = subjectList;
    }

    public Classs(Integer classsid) {
        this.classsid = classsid;
    }

    // Getters and Setters generated by Lombok
}
